site_name: Web Programming 23-24
plugins:
    - mkdocs-video
nav:
  - 'Главная': 'index.md'
  - 'ЛР 1': '1.md'
  - 'ЛР 2': '2.md'
  - 'ЛР 3':
      - "Описание": 3/description.md
      - "Эндпоинты": 3/endpoints.md
      - "Авторизация": 3/authorization.md
      - "Практика": 3/practice.md